name: crucible-ci

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - LICENSE
      - '**.md'
      - '.github/rulesets/**'
      - .github/workflows/run-crucible-tracking.yaml
      - .github/workflows/crucible-merged.yaml
      - .github/workflows/faux-crucible-ci.yaml
      - 'docs/**'
  workflow_dispatch:

jobs:
  call-benchmark-crucible-ci:
    uses: perftool-incubator/crucible-ci/.github/workflows/benchmark-crucible-ci.yaml@main
    with:
      ci_target: "hwnoise"
      ci_target_branch: "${{ github.ref }}"
      github_workspace: "$GITHUB_WORKSPACE"
    secrets:
      ci_registry_auth: ${{ secrets.CRUCIBLE_CI_ENGINES_REGISTRY_AUTH }}
      quay_oauth_token: ${{ secrets.CRUCIBLE_QUAYIO_OAUTH_TOKEN }}
