name: faux-crucible-ci

on:
  pull_request:
    branches: [ main ]
    paths:
      - LICENSE
      - '**.md'
      - .github/workflows/run-crucible-tracking.yaml
      - .github/workflows/crucible-merged.yaml
      - .github/workflows/faux-crucible-ci.yaml
      - 'docs/**'

jobs:
  call-benchmark-crucible-ci:
    uses: perftool-incubator/crucible-ci/.github/workflows/faux-benchmark-crucible-ci.yaml@main
